name: BlockShuffle
version: 1.0
author: Jaymun
main: com.jaymun.BlockShuffle
description: If you want what you've looked then you need to keep looking at it forever!!! Or just mine it before you look away, otherwise you lost it